slice_name: Order Status
viz_type: echarts_area
params:
  adhoc_filters: []
  annotation_layers: []
  color_scheme: supersetColors
  comparison_type: values
  dashboards:
  - 9
  datasource: 22__table
  extra_form_data: {}
  forecastInterval: 0.8
  forecastPeriods: 10
  granularity_sqla: order_date
  groupby:
  - status
  legendOrientation: top
  legendType: scroll
  markerSize: 6
  metrics:
  - count
  only_total: true
  opacity: 0.2
  order_desc: true
  rich_tooltip: true
  row_limit: 10000
  seriesType: line
  show_empty_columns: true
  show_legend: true
  slice_id: 80
  stack: Stack
  time_grain_sqla: P1D
  time_range: No filter
  tooltipTimeFormat: smart_date
  truncate_metric: true
  viz_type: echarts_area
  x_axis_time_format: smart_date
  x_axis_title_margin: 15
  y_axis_bounds:
  - null
  - null
  y_axis_format: SMART_NUMBER
  y_axis_title_margin: 15
  y_axis_title_position: Left
cache_timeout: null
uuid: 7257b759-7b16-43b7-9521-a7b38039177d
version: 1.0.0
dataset_uuid: 67098f60-24c1-492c-9508-16c5b84c7970
