slice_name: Order Payments
viz_type: echarts_area
params:
  datasource: 392__table
  viz_type: echarts_area
  granularity_sqla: order_date
  time_grain_sqla: P1D
  time_range: No filter
  metrics:
  - expressionType: SIMPLE
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: credit_card_amount
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 7612
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: FLOAT64
      type_generic: 0
      verbose_name: null
      warning_markdown: null
    aggregate: SUM
    sqlExpression: null
    isNew: false
    hasCustomLabel: true
    label: Credit Card
    optionName: metric_taagu8juhnr_nv29vujaqvd
  - expressionType: SIMPLE
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: coupon_amount
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 7613
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: FLOAT64
      type_generic: 0
      verbose_name: null
      warning_markdown: null
    aggregate: SUM
    sqlExpression: null
    isNew: false
    hasCustomLabel: true
    label: Coupon
    optionName: metric_3xyrkg10r2p_uwcim3fz41r
  - expressionType: SIMPLE
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: bank_transfer_amount
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 7614
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: FLOAT64
      type_generic: 0
      verbose_name: null
      warning_markdown: null
    aggregate: SUM
    sqlExpression: null
    isNew: false
    hasCustomLabel: true
    label: Bank Transfer
    optionName: metric_dwbqt0mmd_psfutiykop
  - expressionType: SIMPLE
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: gift_card_amount
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 7615
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: FLOAT64
      type_generic: 0
      verbose_name: null
      warning_markdown: null
    aggregate: SUM
    sqlExpression: null
    isNew: false
    hasCustomLabel: true
    label: Gift Card
    optionName: metric_6i78ltoc34k_v3fmcspgun
  groupby: []
  adhoc_filters: []
  order_desc: true
  row_limit: 10000
  truncate_metric: true
  show_empty_columns: true
  rolling_type: cumsum
  comparison_type: values
  annotation_layers: []
  forecastPeriods: 10
  forecastInterval: 0.8
  x_axis_title_margin: 15
  y_axis_title_margin: 15
  y_axis_title_position: Left
  color_scheme: supersetColors
  seriesType: line
  opacity: 0.2
  only_total: true
  markerSize: 6
  show_legend: true
  legendType: scroll
  legendOrientation: top
  x_axis_time_format: smart_date
  rich_tooltip: true
  tooltipTimeFormat: smart_date
  y_axis_format: SMART_NUMBER
  y_axis_bounds:
  - null
  - null
  extra_form_data: {}
  dashboards:
  - 8
cache_timeout: null
uuid: 7954c1c1-8a52-4f92-a54f-4dba241c43d0
version: 1.0.0
dataset_uuid: 0b80c6b3-ca9c-4952-998e-853a777c2fd4
